//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectSQLServerAndUsingAjaxJQuery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NamNhanVienGioi
    {
        public int EmployeeID { get; set; }
        public Nullable<int> sldn { get; set; }
        public string Name { get; set; }
    }
}
