//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectSQLServerAndUsingAjaxJQuery.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NorthwindEntities2 : DbContext
    {
        public NorthwindEntities2()
            : base("name=NorthwindEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Order_Detail> Order_Details { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Shipper> Shippers { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<CacKhachHangMy> CacKhachHangMies { get; set; }
        public virtual DbSet<NamNhanVienGioi> NamNhanVienGiois { get; set; }
        public virtual DbSet<Tim10khachhang> Tim10khachhang { get; set; }
    
        [DbFunction("NorthwindEntities2", "DSDonHangCuaKhachHang")]
        public virtual IQueryable<DSDonHangCuaKhachHang_Result> DSDonHangCuaKhachHang(string maKhachHang)
        {
            var maKhachHangParameter = maKhachHang != null ?
                new ObjectParameter("MaKhachHang", maKhachHang) :
                new ObjectParameter("MaKhachHang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<DSDonHangCuaKhachHang_Result>("[NorthwindEntities2].[DSDonHangCuaKhachHang](@MaKhachHang)", maKhachHangParameter);
        }
    
        [DbFunction("NorthwindEntities2", "DSDonHangCuaQuocGiaKhachHang1")]
        public virtual IQueryable<DSDonHangCuaQuocGiaKhachHang1_Result> DSDonHangCuaQuocGiaKhachHang1(string tenQuocGia)
        {
            var tenQuocGiaParameter = tenQuocGia != null ?
                new ObjectParameter("TenQuocGia", tenQuocGia) :
                new ObjectParameter("TenQuocGia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<DSDonHangCuaQuocGiaKhachHang1_Result>("[NorthwindEntities2].[DSDonHangCuaQuocGiaKhachHang1](@TenQuocGia)", tenQuocGiaParameter);
        }
    
        [DbFunction("NorthwindEntities2", "DSDonHangCuaQuocGiaKhachHang2")]
        public virtual IQueryable<DSDonHangCuaQuocGiaKhachHang2_Result> DSDonHangCuaQuocGiaKhachHang2(string tenQuocGia)
        {
            var tenQuocGiaParameter = tenQuocGia != null ?
                new ObjectParameter("TenQuocGia", tenQuocGia) :
                new ObjectParameter("TenQuocGia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<DSDonHangCuaQuocGiaKhachHang2_Result>("[NorthwindEntities2].[DSDonHangCuaQuocGiaKhachHang2](@TenQuocGia)", tenQuocGiaParameter);
        }
    
        [DbFunction("NorthwindEntities2", "DSHangHoaCuaKhachHang1")]
        public virtual IQueryable<DSHangHoaCuaKhachHang1_Result> DSHangHoaCuaKhachHang1(string maKhachHang)
        {
            var maKhachHangParameter = maKhachHang != null ?
                new ObjectParameter("MaKhachHang", maKhachHang) :
                new ObjectParameter("MaKhachHang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<DSHangHoaCuaKhachHang1_Result>("[NorthwindEntities2].[DSHangHoaCuaKhachHang1](@MaKhachHang)", maKhachHangParameter);
        }
    
        [DbFunction("NorthwindEntities2", "DSHangHoaCuaKhachHang2")]
        public virtual IQueryable<DSHangHoaCuaKhachHang2_Result> DSHangHoaCuaKhachHang2(string maKhachHang)
        {
            var maKhachHangParameter = maKhachHang != null ?
                new ObjectParameter("MaKhachHang", maKhachHang) :
                new ObjectParameter("MaKhachHang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<DSHangHoaCuaKhachHang2_Result>("[NorthwindEntities2].[DSHangHoaCuaKhachHang2](@MaKhachHang)", maKhachHangParameter);
        }
    
        [DbFunction("NorthwindEntities2", "fn_DonHangNhanVien")]
        public virtual IQueryable<fn_DonHangNhanVien_Result> fn_DonHangNhanVien(Nullable<int> maNV, Nullable<System.DateTime> nam)
        {
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_DonHangNhanVien_Result>("[NorthwindEntities2].[fn_DonHangNhanVien](@MaNV, @Nam)", maNVParameter, namParameter);
        }
    
        public virtual ObjectResult<DSDonHangTungNhanVien_Result> DSDonHangTungNhanVien(string maNhanVien)
        {
            var maNhanVienParameter = maNhanVien != null ?
                new ObjectParameter("MaNhanVien", maNhanVien) :
                new ObjectParameter("MaNhanVien", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DSDonHangTungNhanVien_Result>("DSDonHangTungNhanVien", maNhanVienParameter);
        }
    
        public virtual ObjectResult<DSDonHangTungNhanVien2_Result> DSDonHangTungNhanVien2(string maNhanVien)
        {
            var maNhanVienParameter = maNhanVien != null ?
                new ObjectParameter("MaNhanVien", maNhanVien) :
                new ObjectParameter("MaNhanVien", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DSDonHangTungNhanVien2_Result>("DSDonHangTungNhanVien2", maNhanVienParameter);
        }
    
        public virtual ObjectResult<DSDonHangTungQuocGia_Result> DSDonHangTungQuocGia(string tenQuocGia)
        {
            var tenQuocGiaParameter = tenQuocGia != null ?
                new ObjectParameter("TenQuocGia", tenQuocGia) :
                new ObjectParameter("TenQuocGia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DSDonHangTungQuocGia_Result>("DSDonHangTungQuocGia", tenQuocGiaParameter);
        }
    
        public virtual ObjectResult<DSKhachHang_Result> DSKhachHang(string tenQuocGia)
        {
            var tenQuocGiaParameter = tenQuocGia != null ?
                new ObjectParameter("TenQuocGia", tenQuocGia) :
                new ObjectParameter("TenQuocGia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DSKhachHang_Result>("DSKhachHang", tenQuocGiaParameter);
        }
    
        public virtual int GiaiPhuongTrinhBacNhat(Nullable<double> a, Nullable<double> b, ObjectParameter kq)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(double));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("b", b) :
                new ObjectParameter("b", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GiaiPhuongTrinhBacNhat", aParameter, bParameter, kq);
        }
    
        public virtual ObjectResult<MaSangThongTin_Result> MaSangThongTin(Nullable<int> masanpham)
        {
            var masanphamParameter = masanpham.HasValue ?
                new ObjectParameter("masanpham", masanpham) :
                new ObjectParameter("masanpham", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MaSangThongTin_Result>("MaSangThongTin", masanphamParameter);
        }
    
        public virtual int ProcThemKHMuc1(string maKH, string tenCT, string thanhPho, string quocGia)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var tenCTParameter = tenCT != null ?
                new ObjectParameter("TenCT", tenCT) :
                new ObjectParameter("TenCT", typeof(string));
    
            var thanhPhoParameter = thanhPho != null ?
                new ObjectParameter("ThanhPho", thanhPho) :
                new ObjectParameter("ThanhPho", typeof(string));
    
            var quocGiaParameter = quocGia != null ?
                new ObjectParameter("QuocGia", quocGia) :
                new ObjectParameter("QuocGia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProcThemKHMuc1", maKHParameter, tenCTParameter, thanhPhoParameter, quocGiaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SLKhachHangTungQuocGia(string tenQuocGia)
        {
            var tenQuocGiaParameter = tenQuocGia != null ?
                new ObjectParameter("TenQuocGia", tenQuocGia) :
                new ObjectParameter("TenQuocGia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SLKhachHangTungQuocGia", tenQuocGiaParameter);
        }
    
        public virtual int SLKhachHangTungQuocGia2(string tenQuocGia, ObjectParameter sLKhachHang)
        {
            var tenQuocGiaParameter = tenQuocGia != null ?
                new ObjectParameter("TenQuocGia", tenQuocGia) :
                new ObjectParameter("TenQuocGia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SLKhachHangTungQuocGia2", tenQuocGiaParameter, sLKhachHang);
        }
    
        public virtual int SLKhachHangTungQuocGia3(string tenQuocGia, ObjectParameter sLKhachHang)
        {
            var tenQuocGiaParameter = tenQuocGia != null ?
                new ObjectParameter("TenQuocGia", tenQuocGia) :
                new ObjectParameter("TenQuocGia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SLKhachHangTungQuocGia3", tenQuocGiaParameter, sLKhachHang);
        }
    
        public virtual int SLKhachHangTungQuocGia4(string tenQuocGia, ObjectParameter sLKhachHang)
        {
            var tenQuocGiaParameter = tenQuocGia != null ?
                new ObjectParameter("TenQuocGia", tenQuocGia) :
                new ObjectParameter("TenQuocGia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SLKhachHangTungQuocGia4", tenQuocGiaParameter, sLKhachHang);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<sp_cau1_Result> sp_cau1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cau1_Result>("sp_cau1");
        }
    
        public virtual ObjectResult<sp_cau1_danhmucsp_Result> sp_cau1_danhmucsp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cau1_danhmucsp_Result>("sp_cau1_danhmucsp");
        }
    
        public virtual ObjectResult<sp_Cau1_DanhMucSPP_Result> sp_Cau1_DanhMucSPP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Cau1_DanhMucSPP_Result>("sp_Cau1_DanhMucSPP");
        }
    
        public virtual ObjectResult<sp_cau2_Result> sp_cau2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cau2_Result>("sp_cau2");
        }
    
        public virtual ObjectResult<sp_cau3_Result> sp_cau3(Nullable<int> maSP)
        {
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cau3_Result>("sp_cau3", maSPParameter);
        }
    
        public virtual ObjectResult<sp_cau4_Result> sp_cau4(Nullable<System.DateTime> ngayBD, Nullable<System.DateTime> ngayKT)
        {
            var ngayBDParameter = ngayBD.HasValue ?
                new ObjectParameter("NgayBD", ngayBD) :
                new ObjectParameter("NgayBD", typeof(System.DateTime));
    
            var ngayKTParameter = ngayKT.HasValue ?
                new ObjectParameter("NgayKT", ngayKT) :
                new ObjectParameter("NgayKT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cau4_Result>("sp_cau4", ngayBDParameter, ngayKTParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
