//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectSQLServerAndUsingAjaxJQuery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tim10khachhang
    {
        public string CustomerID { get; set; }
        public string CompanyName { get; set; }
        public string Dia_chi { get; set; }
        public Nullable<int> Total_Orders { get; set; }
    }
}
